grid_map_ros:
  ros__parameters:
    input_pointcloud_topic: "/roi_point_cloud"
    output_grid_map_topic: "/grid_map"
    resolution: 0.1
    frame_id: "livox_frame"
    min_x: 0.0
    max_x: 10.0
    min_y: -5.0
    max_y: 5.0
    min_z: 0.0
    max_z: 3.0

